# is this not getting pushed? s
name: pullstations

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Overwrite file
        uses: "isaiahdwest/res_ev/write-file-action@master"
        with:
          path: pull_dc_chargers.py
          write-mode: overwrite
          contents: |
            console.log('some contents')
      - name: Commit & Push
        uses: isaiahdwest/res_ev/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'
